name: Lint
on:
  push:
    branches:
    - main
  schedule:
  # Run everyday at 8:00 AM (See https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html#tag_20_25_07)
  - cron: "0 8 * * *"

permissions:
  contents: read

jobs:
  actionlint:
    name: GitHub Actions
    runs-on: ubuntu-latest
    env:
      REPO: https://github.com/rhysd/actionlint
      VERSION: 1.6.13
    steps:
      - uses: actions/checkout@v4

      - name: Setup actionlint
        run: |
          set -euo pipefail && \
          echo "::add-matcher::.github/matchers/actionlint.json" && \
          echo "Downloading '${REPO}/releases/download/v${VERSION}/actionlint_${VERSION}_linux_amd64.tar.gz'..."
          curl -L "${REPO}/releases/download/v${VERSION}/actionlint_${VERSION}_linux_amd64.tar.gz" \
          | tar xz -C '/usr/local/bin' && \
          echo "actionlint -version:" &&
          actionlint -version

      - run: actionlint -color

  markdown-link-check:
    name: Markdown URLs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        file-extension: .markdown
