name: Lint
on:
  push:
    branches:
    - main
  schedule:
  # Run everyday at 8:00 AM (See https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html#tag_20_25_07)
  - cron: "0 8 * * *"

permissions:
  contents: read

jobs:
  markdown-link-check:
    name: Markdown URLs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        file-extension: .markdown
